CREATE TABLE [kt_枝番工事] (
    [データ年月（受注計上年月）] LONG,
    [基本工事コード] TEXT,
    [枝番工事コード] TEXT,
    [追加工事名称] TEXT,
    [工事価格] TEXT,
    [受注期] INTEGER,
    [受注Q] INTEGER,
    [受注月] INTEGER,
    [受注計上日_日付型] DATETIME,
    [完工期] INTEGER,
    [完工Q] INTEGER,
    [完工月] INTEGER,
    [完工日_日付型] DATETIME,
    [一件工事判定] TEXT,
    [リニューアル環境区分] LONG,
    [リニューアル環境区分名] TEXT,
    [官民区分] TEXT,
    [官民区分名] TEXT,
    [発注者コード] TEXT,
    [発注者略称] TEXT,
    [企業グループコード] TEXT,
    [企業グループ名] TEXT,
    [用途大区分] TEXT,
    [用途大区分名] TEXT,
    [構造区分] TEXT,
    [構造区分名] TEXT,
    [地下階数] TEXT,
    [地上階数] TEXT,
    [塔屋階数] TEXT,
    [建築面積] DOUBLE,
    [延床面積] DOUBLE,
    [施工管轄組織コード] TEXT,
    [施工管轄組織名] TEXT,
    [郵便番号_施工場所] TEXT,
    [施工場所名to番地] TEXT,
    CONSTRAINT PK_kt_枝番工事 PRIMARY KEY ([枝番工事コード])
);