CREATE TABLE [at_原価S_基本工事] (
    [基本工事コード] TEXT,
    [基本工事名] TEXT,
    [工事価格] CURRENCY,
    [工事原価(経費込)] CURRENCY,
    [予定利益] CURRENCY,
    [粗利率] DOUBLE,
    [直接工事費] CURRENCY,
    [経費] CURRENCY,
    [作業所経費] CURRENCY,
    [率] DOUBLE,
    [共通経費] CURRENCY,
    [率2] DOUBLE,
    [既払高：総額] CURRENCY,
    [既払高：経費] CURRENCY,
    [今後支払予定] CURRENCY,
    [当月より前の支払金額] CURRENCY,
    [当月支払金額] CURRENCY,
    [設計料・他] CURRENCY,
    [当月以降予定金額] CURRENCY,
    [行分類] TEXT
);